### PR TITLE
update to Swift 4.0, tweak pod and project files

### PR DESCRIPTION
**Pull request by donmowry**

### CODE REVIEW

**Comment by dcoufal** [comment]
Thanks Don! I've been on holiday and just got back. I'll look at this later in the day and hopefully do a release after a merge.

**Comment by donmowry** [comment]
Welcome back 👋! No rush, just finally catching up

**Review by dcoufal — APPROVED** [review]
1.2.0 sounds good to me.

**Comment by dcoufal** [comment]
@donmowry I've tagged the 1.2.0 release. I suspect you are not waiting on me, but just in case you were.

Thanks for the PR!

**Pull request merged**
